CREATE TABLE `booklog` (
	`isbn13` VARCHAR(13) NOT NULL COLLATE 'utf16_unicode_520_ci',
	`isbn10` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	`bookname` VARCHAR(50) NOT NULL COLLATE 'utf16_unicode_520_ci',
	`author` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	`publisher` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	`genre` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	`issuedate` DATE NULL DEFAULT NULL,
	`getdate` DATE NOT NULL,
	`readdate` DATE NULL DEFAULT NULL,
	`ownership` TINYINT(1) NULL DEFAULT NULL,
	`purchase` INT(11) NULL DEFAULT '0',
	`library` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	`overview` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	`impressions` TEXT NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	`state` INT(10) NULL DEFAULT '0',
	`coverimg` VARCHAR(41) NULL DEFAULT NULL COLLATE 'utf16_unicode_520_ci',
	PRIMARY KEY (`isbn13`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
COMMENT ON TABLE booklog is '読書履歴';
COMMENT ON COLUMN booklog.isbn13 is 'ISBN13';
COMMENT ON COLUMN booklog.isbn10 is 'ISBN10';
COMMENT ON COLUMN booklog.bookname is '書名';
COMMENT ON COLUMN booklog.author is '著者';
COMMENT ON COLUMN booklog.publisher`  is '出版社'; 
COMMENT ON COLUMN booklog.genre is '分類';
COMMENT ON COLUMN booklog.issuedate is '発行日';
COMMENT ON COLUMN booklog.getdate is '取得日';
COMMENT ON COLUMN booklog.readdate is '読了日';
COMMENT ON COLUMN booklog.ownership is '所有';
COMMENT ON COLUMN booklog.purchase is '値段';
COMMENT ON COLUMN booklog.library is '図書館';
COMMENT ON COLUMN booklog.overview is '概要';
COMMENT ON COLUMN booklog.impressions is '感想';
COMMENT ON COLUMN booklog.state is '状態';
COMMENT ON COLUMN booklog.coverimg is '表紙';
